### ISSUE TITLE
[BUG] After castling, rook cannot move to all of its valid moves. 

### ISSUE THREAD

**Issue by camero1993** [bkwon21/ChessApp#19]
Castled the rook on the right, and afterward it could not move at all. I castled the rook on the left and after that, it could only move forward for one move. After that it could move as normal.

**Comment by bkwon21** [comment]
Fixed in commit [#66c7cd2](https://github.com/bkwon21/ChessApp/tree/66c7cd2bb6d1c0f714c50a2668cf2d64925181e8)
